from Model.Transformer import Transformer
from Model.CNN import CNN
from Model.Transfomer_domain_adaptive import Transformer_domain
from Model.FCSTGNN import FC_STGNN_RUL
from Model.AGCNN import AGCNN
from Model.LeNet import LeNet
from Model.LSTM import LSTM
from Model.Autoformer import Autoformer
from Model.PatchTST import PatchTST
from Model.Dual_Mixer import DualMLPMixer
from Model.AIGCN import AIGCN
from Model.AIGCN_AS import AIGCN_AS
from Model.AIGCN_AS_A import AIGCN_AS_A
from Model.AIGCN_AS_T import AIGCN_AS_T
from Model.AIGCN_Cos import AIGCN_Cos
from Model.PINN import PINN
from Model.CDSG import CDSG
from Model.SDAGCN import SDAGCN
from Model.DPDG_p import DPDG_p
